---
- name: Provisionning webservers group
  hosts: webservers
  become: yes
  vars:
    user: root
    group: docker
    traefik_dir: /var/www/traefik
    home_dir: /root
  roles:
    - { role: user, tags: user }
    - { role: tools, tags: tools }
    - { role: docker, tags: docker }
    - { role: traefik, tags: traefik }
    - { role: watchtower, tags: watchtower }
