---
- name: Provisionning webservers group
  hosts: webservers
  become: yes
  vars:
    user: root
    group: docker
    traefik_dir: /var/www/traefik
    home_dir: /root
  roles:
    - user
    - tools
    - docker
    - traefik
    - watchtower
