---
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    mode: 0600

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: "{{ traefik_dir }}/traefik.toml"
    mode: 0600

- name: Create the web network
  docker_network:
    name: web

- name: Create the traefik container
  docker_container:
    name: traefik
    image: traefik:1.7
    restart_policy: unless-stopped
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml"
      - "{{ traefik_dir }}/acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.frontend.rule: "Host:{{ traefik_api_url }}"
      traefik.docker.network: "web"
      traefik.port: "8080"
      traefik.enable: "true"
    env:
      GANDIV5_API_KEY: "{{ gandi_api_key }}"
